# Generated by Django 3.2.8 on 2022-02-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricprop',
            old_name='Fabric',
            new_name='fabric',
        ),
        migrations.RenameField(
            model_name='fabricprop',
            old_name='Fabric_Type',
            new_name='fabric_Type',
        ),
    ]
